# -*- coding: utf-8 -*-
"""Proyecto Nº 01

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kOuDnDaSYN3fGI2nuGGQqe1INSsHJXvm
"""

import pandas as pd
import numpy as np

"""Ejercicio 1"""

ventas = {}
días = int(input('Número de los últimos días: '))
for i in range(días):
  i = 1+i
  ventas[i] = int(input('Introduce las ventas de hace ' + str(i) +' día(s): '))
lista1 = ventas.items()
type(lista1) 
lista1 = list(lista1)
df1 = pd.DataFrame((lista1),columns = ['Día','Venta'])
df1

"""Ejercicio 2"""

def ingreso_mensual(ingreso):
  ingreso = pd.Series(ingreso)
  estadística = pd.Series([ingreso.min(), ingreso.max(), ingreso.mean()], index=['Min', 'Max', 'Media'])
  return estadística
ingresos_clientes = {}
clientes = int(input('Ingrese número de clientes '))
for i in range(clientes):
  i = 1+i
  ingresos_clientes[i] = int(input('Introduce el ingreso mensual del cliente ' + str(i) +' : '))
print("Estadísticas")
ingreso_mensual(ingresos_clientes)

"""Ejercicio 3"""

Mes = ["Enero","Febrero","Marzo","Abril","Mayo"]
Ventas = [30500,35600,28300,33900,42500]
Gastos = [22000,23450,18100,35700,32450]

df3 = pd.DataFrame()
df3['Mes'] = Mes
df3['Ventas'] = Ventas
df3['Gastos'] = Gastos
df3

df3['Columna1']= df3.Gastos/df3.Ventas*100
df3

def condicion(data):
  if(data['Ventas']>= 30000):
    return "Meta Superada"
  else:
    return "Meta no Superada"

df3['Columna2']=df3.apply(condicion,axis=1)
df3

def condicion2(data):
  if(data['Gastos']> data['Ventas']):
    return data['Gastos'] - data['Ventas']
  else:
    return 0
df3['Sobregasto']=df3.apply(condicion2,axis=1)
df3

df3['Ventas'].iloc[2:].sum()

df3['Gastos'].iloc[1:4].sum()

"""Ejercicio 4 """

df4 = pd.read_csv("Data - Riesgos.csv",encoding ='cp1252')

df4

df4.columns

df4.info()

df4.isnull().sum()

df4.head(10)

df4.tail(10)

ar4 = df4.head(100)[['ID', 'edad', 'meses', 'max_ant', 'ingreso', 'score', 'tipo_vivienda',
       'zona', 'nivel', 'riesgo']].to_numpy()

ar4